name: 签到

on:
  # github定时工作流，但时间不是东八区。东0区，北京时间减8小时。
  schedule:
    - cron: '20 22,6 * * *'
  # 点击star收藏，则手动执行此github工作流
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'watch' && github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    - name: 安装依赖包
      run: |
        pip install -r requirements.txt
    - name: 执行签到
      # USER 和PWD参数支持多个 ，读取进user_list 和 pwd_list 。参数之间分隔符是'\n'换行【第40行】
      # 第65行运行py签到文件 ：checkin.py只签一次 ；check_multi.py 多线程签多次
      run: |
        echo -n "This IP is: " 
        curl -s ifconfig.me
        echo ' '
        
        echo $(date +%T)
        
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        
        user_list=()
        pwd_list=()

        IFS=$'\n'     

        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done

        for p in ${pwd[*]}
        do
        pwd_list[${#pwd_list[*]}]=${p}
        done

        user_num=${#user_list[*]}
        pwd_num=${#pwd_list[*]}

        if [ $user_num != $pwd_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $user_num 个账号，即将开始签到"
        fi

        for ((i=0;i<$user_num;i++))
        do
        python3 checkin_multi.py <<EOF
        ${user_list[$i]}
        ${pwd_list[$i]}
        EOF
        done
